//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5477
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonateWin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DonateWin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap add_icon {
            get {
                object obj = ResourceManager.GetObject("add_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 현재 입력한 데이타를 저장하시겠습니까?  Yes 를 선택하면 저장이 되고 No 를 선택하면 삭제가 됩니다..
        /// </summary>
        internal static string Alert_Save {
            get {
                return ResourceManager.GetString("Alert_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 헌금 .
        /// </summary>
        internal static string Application_Name {
            get {
                return ResourceManager.GetString("Application_Name", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap bg {
            get {
                object obj = ResourceManager.GetObject("bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bg1 {
            get {
                object obj = ResourceManager.GetObject("bg1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 헌금 종류를 선택해 주시길 바랍니다..
        /// </summary>
        internal static string Check_DonateType {
            get {
                return ResourceManager.GetString("Check_DonateType", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap close_icon {
            get {
                object obj = ResourceManager.GetObject("close_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 지우시겠습니까? .
        /// </summary>
        internal static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 헌금 금액이 맞지 않습니다. 확인해 주시길 바랍니다..
        /// </summary>
        internal static string DonateAmountError {
            get {
                return ResourceManager.GetString("DonateAmountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 헌금입력에 실패했습니다..
        /// </summary>
        internal static string DonateInsertError {
            get {
                return ResourceManager.GetString("DonateInsertError", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap edit_icon {
            get {
                object obj = ResourceManager.GetObject("edit_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipcode 를 입력해 주시길 바랍니다..
        /// </summary>
        internal static string Enter_your_zipcode {
            get {
                return ResourceManager.GetString("Enter_your_zipcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured. Please Contact a administrator .
        /// </summary>
        internal static string Error_Message {
            get {
                return ResourceManager.GetString("Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 교인번호가 정확하지 않습니다. .
        /// </summary>
        internal static string Invalid_Memberid {
            get {
                return ResourceManager.GetString("Invalid_Memberid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 명단에 없는 교인명입니다..
        /// </summary>
        internal static string Invalid_Name {
            get {
                return ResourceManager.GetString("Invalid_Name", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap login_bg {
            get {
                object obj = ResourceManager.GetObject("login_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap login_button {
            get {
                object obj = ResourceManager.GetObject("login_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 로그인에 실패 했습니다..
        /// </summary>
        internal static string LoginErrorCaption {
            get {
                return ResourceManager.GetString("LoginErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry, but you used an User ID and/or password that doesn&apos;t match our records. Please try again..
        /// </summary>
        internal static string LoginErrorMessage {
            get {
                return ResourceManager.GetString("LoginErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 새 교인 .
        /// </summary>
        internal static string NewDonate {
            get {
                return ResourceManager.GetString("NewDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No relevant information was found for your request.
        /// </summary>
        internal static string No_result {
            get {
                return ResourceManager.GetString("No_result", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ok_icon {
            get {
                object obj = ResourceManager.GetObject("ok_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap print_icon {
            get {
                object obj = ResourceManager.GetObject("print_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap print24x24 {
            get {
                object obj = ResourceManager.GetObject("print24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Remove {
            get {
                object obj = ResourceManager.GetObject("Remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 현재 데이타 베이스에 연결 할수가 없습니다. 잠시 후 다시 시도해 주시길 바랍니다..
        /// </summary>
        internal static string SqlError {
            get {
                return ResourceManager.GetString("SqlError", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Sync {
            get {
                object obj = ResourceManager.GetObject("Sync", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 현재 저장되지 않은 헌금내역이 있습니다.  저장되지 않은 내역을 불러오시겠습니까?.
        /// </summary>
        internal static string UnsavedFile {
            get {
                return ResourceManager.GetString("UnsavedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 현재 저장되지 않은 헌금 내역이 없습니다..
        /// </summary>
        internal static string UnsavedFile_Result {
            get {
                return ResourceManager.GetString("UnsavedFile_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 유저아이디를 확인해 주시길 바랍니다..
        /// </summary>
        internal static string Verify_userid {
            get {
                return ResourceManager.GetString("Verify_userid", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Yes {
            get {
                object obj = ResourceManager.GetObject("Yes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
