//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandWin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LandWin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Add_16X16 {
            get {
                object obj = ResourceManager.GetObject("Add_16X16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Add_24x24 {
            get {
                object obj = ResourceManager.GetObject("Add_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Add_32X32 {
            get {
                object obj = ResourceManager.GetObject("Add_32X32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 주소.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 나이.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 교회 행정 관리 시스템.
        /// </summary>
        internal static string Application_Name {
            get {
                return ResourceManager.GetString("Application_Name", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Apply {
            get {
                object obj = ResourceManager.GetObject("Apply", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_left {
            get {
                object obj = ResourceManager.GetObject("arrow_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 참석자.
        /// </summary>
        internal static string Attendents {
            get {
                return ResourceManager.GetString("Attendents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 세례.
        /// </summary>
        internal static string Baptism {
            get {
                return ResourceManager.GetString("Baptism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 세례년도.
        /// </summary>
        internal static string Baptism_Date {
            get {
                return ResourceManager.GetString("Baptism_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 세례 설정.
        /// </summary>
        internal static string Baptism_Setting {
            get {
                return ResourceManager.GetString("Baptism_Setting", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap bg {
            get {
                object obj = ResourceManager.GetObject("bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bg_login {
            get {
                object obj = ResourceManager.GetObject("bg_login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bg1 {
            get {
                object obj = ResourceManager.GetObject("bg1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 성경.
        /// </summary>
        internal static string Bible {
            get {
                return ResourceManager.GetString("Bible", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap BindingNavigatorAddNewItem {
            get {
                object obj = ResourceManager.GetObject("BindingNavigatorAddNewItem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BindingNavigatorDeleteItem {
            get {
                object obj = ResourceManager.GetObject("BindingNavigatorDeleteItem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 생년월일.
        /// </summary>
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Boss {
            get {
                object obj = ResourceManager.GetObject("Boss", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bt_cancel {
            get {
                object obj = ResourceManager.GetObject("bt_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bt_login {
            get {
                object obj = ResourceManager.GetObject("bt_login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Calendar {
            get {
                object obj = ResourceManager.GetObject("Calendar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cancel {
            get {
                object obj = ResourceManager.GetObject("Cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 순.
        /// </summary>
        internal static string Cell {
            get {
                return ResourceManager.GetString("Cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 순 관리.
        /// </summary>
        internal static string Cell_Manage {
            get {
                return ResourceManager.GetString("Cell_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 순정보 수정.
        /// </summary>
        internal static string Cell_modify {
            get {
                return ResourceManager.GetString("Cell_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 순명.
        /// </summary>
        internal static string Cell_name {
            get {
                return ResourceManager.GetString("Cell_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 순 설정.
        /// </summary>
        internal static string Cell_Setting {
            get {
                return ResourceManager.GetString("Cell_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 순모임 일자.
        /// </summary>
        internal static string Celldate {
            get {
                return ResourceManager.GetString("Celldate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 휴대폰.
        /// </summary>
        internal static string Cellphone {
            get {
                return ResourceManager.GetString("Cellphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 순모임 장소.
        /// </summary>
        internal static string CellPlace {
            get {
                return ResourceManager.GetString("CellPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 순 보고서 관리.
        /// </summary>
        internal static string CellReport_Manage {
            get {
                return ResourceManager.GetString("CellReport_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 세대주 변경을 하시겠습니까?.
        /// </summary>
        internal static string ChangeFamilyQue {
            get {
                return ResourceManager.GetString("ChangeFamilyQue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 헌금 종류를 선택해 주시길 바랍니다. .
        /// </summary>
        internal static string Check_DonateType {
            get {
                return ResourceManager.GetString("Check_DonateType", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap check_icon {
            get {
                object obj = ResourceManager.GetObject("check_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 뉴저지초대교회.
        /// </summary>
        internal static string Church_Name {
            get {
                return ResourceManager.GetString("Church_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 도시명.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap close_icon {
            get {
                object obj = ResourceManager.GetObject("close_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap close_page {
            get {
                object obj = ResourceManager.GetObject("close_page", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 변경된 사항을 저장하기 않고 닫으시겠습니까?.
        /// </summary>
        internal static string Closeandsave {
            get {
                return ResourceManager.GetString("Closeandsave", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap collapes_icon_left {
            get {
                object obj = ResourceManager.GetObject("collapes_icon_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap collapes_icon_left1 {
            get {
                object obj = ResourceManager.GetObject("collapes_icon_left1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap collapes_icon_right {
            get {
                object obj = ResourceManager.GetObject("collapes_icon_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap collapse_icon {
            get {
                object obj = ResourceManager.GetObject("collapse_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 수료일.
        /// </summary>
        internal static string CompleteDate {
            get {
                return ResourceManager.GetString("CompleteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 환경 설정.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 심방 내용.
        /// </summary>
        internal static string Contents {
            get {
                return ResourceManager.GetString("Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 강의명.
        /// </summary>
        internal static string CourseName {
            get {
                return ResourceManager.GetString("CourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 현재 세대주 입니다..
        /// </summary>
        internal static string Current_FamilyOwner {
            get {
                return ResourceManager.GetString("Current_FamilyOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 정말 삭제 하시겠습니까?  .
        /// </summary>
        internal static string Delete_Ask {
            get {
                return ResourceManager.GetString("Delete_Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 소속.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 분류.
        /// </summary>
        internal static string Division {
            get {
                return ResourceManager.GetString("Division", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Document_16x16 {
            get {
                object obj = ResourceManager.GetObject("Document_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap documents {
            get {
                object obj = ResourceManager.GetObject("documents", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 헌금.
        /// </summary>
        internal static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap donate_24x24 {
            get {
                object obj = ResourceManager.GetObject("donate_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap donate_icon {
            get {
                object obj = ResourceManager.GetObject("donate_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap donate_icon_16x116 {
            get {
                object obj = ResourceManager.GetObject("donate_icon_16x116", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 헌금 관리.
        /// </summary>
        internal static string Donate_Manage {
            get {
                return ResourceManager.GetString("Donate_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 입력하신 금액 과 총계와 맞지 않습니다. .
        /// </summary>
        internal static string DonateAmountError {
            get {
                return ResourceManager.GetString("DonateAmountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 헌금 내역부.
        /// </summary>
        internal static string DonateBookes {
            get {
                return ResourceManager.GetString("DonateBookes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 입력하신 헌금내용이 정확하지 않습니다.  다시 입력해 주시길 바랍니다..
        /// </summary>
        internal static string DonateInsertError {
            get {
                return ResourceManager.GetString("DonateInsertError", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Download {
            get {
                object obj = ResourceManager.GetObject("Download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이미 등록된 교인입니다..
        /// </summary>
        internal static string Duplicated_assign {
            get {
                return ResourceManager.GetString("Duplicated_assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이미 Assign 된 직책입니다..
        /// </summary>
        internal static string Duplicated_cellrole {
            get {
                return ResourceManager.GetString("Duplicated_cellrole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이미 입력한 교인입니다..
        /// </summary>
        internal static string Duplicated_Insert {
            get {
                return ResourceManager.GetString("Duplicated_Insert", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap edit_icon {
            get {
                object obj = ResourceManager.GetObject("edit_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edu {
            get {
                object obj = ResourceManager.GetObject("edu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edu_16x16 {
            get {
                object obj = ResourceManager.GetObject("edu_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edu_16x161 {
            get {
                object obj = ResourceManager.GetObject("edu_16x161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 교육 관리.
        /// </summary>
        internal static string Education_Manage {
            get {
                return ResourceManager.GetString("Education_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이메일.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 영어이름.
        /// </summary>
        internal static string En_Name {
            get {
                return ResourceManager.GetString("En_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 종료일.
        /// </summary>
        internal static string Enddate {
            get {
                return ResourceManager.GetString("Enddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 유효하지 않는 Zipcode 입니다..
        /// </summary>
        internal static string Enter_your_zipcode {
            get {
                return ResourceManager.GetString("Enter_your_zipcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이미 등록되어 있습니다. .
        /// </summary>
        internal static string Err_Duplicated {
            get {
                return ResourceManager.GetString("Err_Duplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 가족이 있는 세대주는 다른 세대로 이전 할 수가 없습니다..
        /// </summary>
        internal static string Error_AddFamilyOwner {
            get {
                return ResourceManager.GetString("Error_AddFamilyOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Saving.
        /// </summary>
        internal static string Error_Save {
            get {
                return ResourceManager.GetString("Error_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 현재 이 기능을 사용할 권한이 없습니다. Adminstrator 에게 문의하시길 바랍니다..
        /// </summary>
        internal static string ErrorMassage_UnAuthorized {
            get {
                return ResourceManager.GetString("ErrorMassage_UnAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Unexpected error occured. Please contact a Administrator.
        /// </summary>
        internal static string ErrorMessage_General {
            get {
                return ResourceManager.GetString("ErrorMessage_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 현재 데이타가 유효하지 않습니다.   확인해 주시길 바랍니다..
        /// </summary>
        internal static string ErrorMessage_Invalid {
            get {
                return ResourceManager.GetString("ErrorMessage_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry, but you used an User ID and/or password that doesn&apos;t match our records. Please try again. (아이디 와 페스워드를 확인해 주시길 바랍니다.).
        /// </summary>
        internal static string ErrorMessage_login {
            get {
                return ResourceManager.GetString("ErrorMessage_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed.
        /// </summary>
        internal static string ErrorMessage_loginCaption {
            get {
                return ResourceManager.GetString("ErrorMessage_loginCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 현재 데이타 베이스에 연결 할수가 없습니다. 잠시 후 다시 시도해 주시길 바랍니다..
        /// </summary>
        internal static string ErrorMessage_SqlException {
            get {
                return ResourceManager.GetString("ErrorMessage_SqlException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 현재 이 기능을 사용할 권항이 없습니다. Administrator 에게 문의하시길 바랍니다..
        /// </summary>
        internal static string ErrorMessage_UnAuthorized {
            get {
                return ResourceManager.GetString("ErrorMessage_UnAuthorized", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap exitButton {
            get {
                object obj = ResourceManager.GetObject("exitButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap expand_icon {
            get {
                object obj = ResourceManager.GetObject("expand_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap export_excel {
            get {
                object obj = ResourceManager.GetObject("export_excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 세대별 주소록.
        /// </summary>
        internal static string FamilyAddrssBook {
            get {
                return ResourceManager.GetString("FamilyAddrssBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 직분.
        /// </summary>
        internal static string Fellowship {
            get {
                return ResourceManager.GetString("Fellowship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 직분 관리.
        /// </summary>
        internal static string Fellowship_Manage {
            get {
                return ResourceManager.GetString("Fellowship_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 임직일.
        /// </summary>
        internal static string Fellowship_regdate {
            get {
                return ResourceManager.GetString("Fellowship_regdate", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap filter_icon {
            get {
                object obj = ResourceManager.GetObject("filter_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Find {
            get {
                object obj = ResourceManager.GetObject("Find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Find_16x16 {
            get {
                object obj = ResourceManager.GetObject("Find_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이름.
        /// </summary>
        internal static string First_name {
            get {
                return ResourceManager.GetString("First_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 세대주명.
        /// </summary>
        internal static string Fmilay {
            get {
                return ResourceManager.GetString("Fmilay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 교인이름.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Gear_Alt_24x24 {
            get {
                object obj = ResourceManager.GetObject("Gear Alt_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap home_24x24 {
            get {
                object obj = ResourceManager.GetObject("home_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 집전화.
        /// </summary>
        internal static string Homephone {
            get {
                return ResourceManager.GetString("Homephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 세대주.
        /// </summary>
        internal static string HouseHolder {
            get {
                return ResourceManager.GetString("HouseHolder", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap import_file {
            get {
                object obj = ResourceManager.GetObject("import_file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap import_file1 {
            get {
                object obj = ResourceManager.GetObject("import_file1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string Initial_Page {
            get {
                return ResourceManager.GetString("Initial_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 존재하지 않는 맴버 ID  입니다.  .
        /// </summary>
        internal static string Invalid_Memberid {
            get {
                return ResourceManager.GetString("Invalid_Memberid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 존재하지 않는 이름입니다..
        /// </summary>
        internal static string Invalid_Name {
            get {
                return ResourceManager.GetString("Invalid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이미 입력되어 있는 헌금입니다. 다시 확인해 주시길 바랍니다..
        /// </summary>
        internal static string Is_duplicate_date {
            get {
                return ResourceManager.GetString("Is_duplicate_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록되어 있지 않은 교인입니다..
        /// </summary>
        internal static string Is_not_donate_member {
            get {
                return ResourceManager.GetString("Is_not_donate_member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 직업.
        /// </summary>
        internal static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 한글 이름.
        /// </summary>
        internal static string Ko_name {
            get {
                return ResourceManager.GetString("Ko_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 성.
        /// </summary>
        internal static string Last_name {
            get {
                return ResourceManager.GetString("Last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 인도자.
        /// </summary>
        internal static string Leader {
            get {
                return ResourceManager.GetString("Leader", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap List {
            get {
                object obj = ResourceManager.GetObject("List", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Load {
            get {
                object obj = ResourceManager.GetObject("Load", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Load_16x16 {
            get {
                object obj = ResourceManager.GetObject("Load_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap login_cross {
            get {
                object obj = ResourceManager.GetObject("login_cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 사용자 ID 와 Password 가 일치하지 않습니다.  확인하시고 Login 하시길 바랍니다..
        /// </summary>
        internal static string Login_fail {
            get {
                return ResourceManager.GetString("Login_fail", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap login_page_background {
            get {
                object obj = ResourceManager.GetObject("login_page_background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo_church {
            get {
                object obj = ResourceManager.GetObject("logo_church", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 기혼.
        /// </summary>
        internal static string Married {
            get {
                return ResourceManager.GetString("Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 교인.
        /// </summary>
        internal static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap member_24x24 {
            get {
                object obj = ResourceManager.GetObject("member_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Member_icon {
            get {
                object obj = ResourceManager.GetObject("Member_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 교인번호.
        /// </summary>
        internal static string Member_id {
            get {
                return ResourceManager.GetString("Member_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 교인 관리.
        /// </summary>
        internal static string Member_Manage {
            get {
                return ResourceManager.GetString("Member_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 개인별 헌금내역 관리.
        /// </summary>
        internal static string MemberDonate {
            get {
                return ResourceManager.GetString("MemberDonate", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap merge {
            get {
                object obj = ResourceManager.GetObject("merge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap merge_16x16 {
            get {
                object obj = ResourceManager.GetObject("merge_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 사역.
        /// </summary>
        internal static string Ministry {
            get {
                return ResourceManager.GetString("Ministry", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ministry_24x24 {
            get {
                object obj = ResourceManager.GetObject("ministry_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 사역 관리.
        /// </summary>
        internal static string Ministry_Manage {
            get {
                return ResourceManager.GetString("Ministry_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 사역명.
        /// </summary>
        internal static string MinistryName {
            get {
                return ResourceManager.GetString("MinistryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 사역직책.
        /// </summary>
        internal static string MinistryRole {
            get {
                return ResourceManager.GetString("MinistryRole", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Modify {
            get {
                object obj = ResourceManager.GetObject("Modify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Move {
            get {
                object obj = ResourceManager.GetObject("Move", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Move1 {
            get {
                object obj = ResourceManager.GetObject("Move1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap msIcon2 {
            get {
                object obj = ResourceManager.GetObject("msIcon2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 헌금 입력 .
        /// </summary>
        internal static string NewDonate {
            get {
                return ResourceManager.GetString("NewDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 새가족.
        /// </summary>
        internal static string NewMember {
            get {
                return ResourceManager.GetString("NewMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 권한이 없습니다..
        /// </summary>
        internal static string No_Authorized {
            get {
                return ResourceManager.GetString("No_Authorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 요청하신 맴버를 찾을 수가 없습니다. .
        /// </summary>
        internal static string No_result {
            get {
                return ResourceManager.GetString("No_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 선택하신 순이 없습니다. 순을 선택해 주시길 바랍니다..
        /// </summary>
        internal static string No_SelectedCell {
            get {
                return ResourceManager.GetString("No_SelectedCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 선택된 내용이 없습니다..
        /// </summary>
        internal static string No_SelectedRow {
            get {
                return ResourceManager.GetString("No_SelectedRow", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap NoPhoto {
            get {
                object obj = ResourceManager.GetObject("NoPhoto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 기도자.
        /// </summary>
        internal static string Prayer {
            get {
                return ResourceManager.GetString("Prayer", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Previous {
            get {
                object obj = ResourceManager.GetObject("Previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap print {
            get {
                object obj = ResourceManager.GetObject("print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap print_icon {
            get {
                object obj = ResourceManager.GetObject("print_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 개인심방내역 .
        /// </summary>
        internal static string Print_InvVisitReport {
            get {
                return ResourceManager.GetString("Print_InvVisitReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 심방내역 리스트.
        /// </summary>
        internal static string Print_VisitReport {
            get {
                return ResourceManager.GetString("Print_VisitReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 교인 정보가 다 지워집니다. .
        /// </summary>
        internal static string Question_DeleteComfirm {
            get {
                return ResourceManager.GetString("Question_DeleteComfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 가족 전체를 지우시겠습니까? (&quot;Do you want to delete family member&quot;).
        /// </summary>
        internal static string Question_DeleteFamily {
            get {
                return ResourceManager.GetString("Question_DeleteFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 교인 정보를 지우시겠습니까?(&quot;Are you sure to delete member&quot;).
        /// </summary>
        internal static string Question_DeleteMember {
            get {
                return ResourceManager.GetString("Question_DeleteMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 정보를 지우시겠습니까? .
        /// </summary>
        internal static string Questions_Delete {
            get {
                return ResourceManager.GetString("Questions_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록일.
        /// </summary>
        internal static string RegDate {
            get {
                return ResourceManager.GetString("RegDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 관계.
        /// </summary>
        internal static string Relationship {
            get {
                return ResourceManager.GetString("Relationship", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Remove_16x16 {
            get {
                object obj = ResourceManager.GetObject("Remove_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Remove_24x24 {
            get {
                object obj = ResourceManager.GetObject("Remove_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Remove_32x32 {
            get {
                object obj = ResourceManager.GetObject("Remove_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reset_icon {
            get {
                object obj = ResourceManager.GetObject("reset_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ribbon_close {
            get {
                object obj = ResourceManager.GetObject("ribbon_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 직책.
        /// </summary>
        internal static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Save_24x24 {
            get {
                object obj = ResourceManager.GetObject("Save_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Save_32x32 {
            get {
                object obj = ResourceManager.GetObject("Save_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search_icon {
            get {
                object obj = ResourceManager.GetObject("search_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search2 {
            get {
                object obj = ResourceManager.GetObject("search2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 소속을 선택해 주세요 .
        /// </summary>
        internal static string Select_SubDiv_message {
            get {
                return ResourceManager.GetString("Select_SubDiv_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 성별.
        /// </summary>
        internal static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 미혼.
        /// </summary>
        internal static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 찬송가.
        /// </summary>
        internal static string Song {
            get {
                return ResourceManager.GetString("Song", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap sort {
            get {
                object obj = ResourceManager.GetObject("sort", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap splite_icon {
            get {
                object obj = ResourceManager.GetObject("splite_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 배우자.
        /// </summary>
        internal static string Spouse {
            get {
                return ResourceManager.GetString("Spouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 시작일.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 주명.
        /// </summary>
        internal static string Statecode {
            get {
                return ResourceManager.GetString("Statecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 교인상태.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 제적 관리.
        /// </summary>
        internal static string Status_Manage {
            get {
                return ResourceManager.GetString("Status_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 교적구분.
        /// </summary>
        internal static string Subdivision {
            get {
                return ResourceManager.GetString("Subdivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 업데이트가 완료 되었습니다..
        /// </summary>
        internal static string Success_Save {
            get {
                return ResourceManager.GetString("Success_Save", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Sync {
            get {
                object obj = ResourceManager.GetObject("Sync", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sync1 {
            get {
                object obj = ResourceManager.GetObject("Sync1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolStripIcon4 {
            get {
                object obj = ResourceManager.GetObject("toolStripIcon4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Transfer {
            get {
                object obj = ResourceManager.GetObject("Transfer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Transfer_24x24 {
            get {
                object obj = ResourceManager.GetObject("Transfer_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap transfer_icon {
            get {
                object obj = ResourceManager.GetObject("transfer_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Undo {
            get {
                object obj = ResourceManager.GetObject("Undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap undo_16x16 {
            get {
                object obj = ResourceManager.GetObject("undo_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Upload {
            get {
                object obj = ResourceManager.GetObject("Upload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap User_24x24 {
            get {
                object obj = ResourceManager.GetObject("User_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Users_24x24 {
            get {
                object obj = ResourceManager.GetObject("Users_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Users_24x241 {
            get {
                object obj = ResourceManager.GetObject("Users_24x241", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 사용자 설정.
        /// </summary>
        internal static string Users_Management {
            get {
                return ResourceManager.GetString("Users_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 교인번호를 입력해 주시길 바랍니다..
        /// </summary>
        internal static string Validate_memberid {
            get {
                return ResourceManager.GetString("Validate_memberid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying UserID and Password.
        /// </summary>
        internal static string Verify_userid {
            get {
                return ResourceManager.GetString("Verify_userid", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap view_icon {
            get {
                object obj = ResourceManager.GetObject("view_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 심방 내역 작성.
        /// </summary>
        internal static string Visit_Edit {
            get {
                return ResourceManager.GetString("Visit_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 심방 관리.
        /// </summary>
        internal static string Visit_Manage {
            get {
                return ResourceManager.GetString("Visit_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 심방 일자.
        /// </summary>
        internal static string VisitDate {
            get {
                return ResourceManager.GetString("VisitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 인도자.
        /// </summary>
        internal static string VisitPastor {
            get {
                return ResourceManager.GetString("VisitPastor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 심방 종류.
        /// </summary>
        internal static string VisitType {
            get {
                return ResourceManager.GetString("VisitType", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap vistaSearch {
            get {
                object obj = ResourceManager.GetObject("vistaSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 기록일.
        /// </summary>
        internal static string Writedate {
            get {
                return ResourceManager.GetString("Writedate", resourceCulture);
            }
        }
    }
}
