//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5477
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dothan.Library.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dothan.Library.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 형제.
        /// </summary>
        internal static string Brother {
            get {
                return ResourceManager.GetString("Brother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        internal static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 자녀.
        /// </summary>
        internal static string Chirdren {
            get {
                return ResourceManager.GetString("Chirdren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date 가 Start Date 이전일 수 없습니다..
        /// </summary>
        internal static string Date_start_end_rule {
            get {
                return ResourceManager.GetString("Date_start_end_rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 직분명은 required 필드입니다..
        /// </summary>
        internal static string Fellowship_Name_unique {
            get {
                return ResourceManager.GetString("Fellowship_Name_unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 여자.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 조부모.
        /// </summary>
        internal static string GrandParent {
            get {
                return ResourceManager.GetString("GrandParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 본인.
        /// </summary>
        internal static string Householder {
            get {
                return ResourceManager.GetString("Householder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InActive.
        /// </summary>
        internal static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 남자.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 기혼.
        /// </summary>
        internal static string Married {
            get {
                return ResourceManager.GetString("Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 조카.
        /// </summary>
        internal static string Nephew {
            get {
                return ResourceManager.GetString("Nephew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 기타.
        /// </summary>
        internal static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 부모.
        /// </summary>
        internal static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 여.
        /// </summary>
        internal static string sFemale {
            get {
                return ResourceManager.GetString("sFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 미혼.
        /// </summary>
        internal static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 자매.
        /// </summary>
        internal static string Sister {
            get {
                return ResourceManager.GetString("Sister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 남.
        /// </summary>
        internal static string sMale {
            get {
                return ResourceManager.GetString("sMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 배우자.
        /// </summary>
        internal static string Spouse {
            get {
                return ResourceManager.GetString("Spouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 사용권한이 없습니다..
        /// </summary>
        internal static string Users_not_authorized {
            get {
                return ResourceManager.GetString("Users_not_authorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying User ID &amp; Password....
        /// </summary>
        internal static string Verifying_Login {
            get {
                return ResourceManager.GetString("Verifying_Login", resourceCulture);
            }
        }
    }
}
